base_url = "https://mypypi.example.com" # The base URL for the server. This is used to generate URLs in the API responses.

[[repositories]]
    slug            = "pypi"                     # The slug is a unique identifier for the repository and will appear in URLs
    simple_url      = "https://pypi.org/simple/" # The URL to the simple repository index
    cache_minutes   = 10                         # [Optional] The number of minutes to cache data for from the upstream index. Defaults to 10
    timeout_seconds = 10                         # [Optional] The number of seconds to wait for a response from the upstream index before returning cached data. Defaults to 10

[[repositories]] # More than one repository can be defined
    slug            = "pytorch"
    simple_url      = "https://download.pytorch.org/whl/"
    cache_minutes   = 10
    timeout_seconds = 10

[[repositories]]
    slug            = "piwheels"
    simple_url      = "https://www.piwheels.org/simple/"
    cache_minutes   = 10
    timeout_seconds = 10

[database]
    url = "postgresql://mypypiuser:mypypipass@db:5432/mypypi" # The URL to the database. This must be a valid SQLAlchemy URL for SQLite or PostgreSQL.
    # SQLite is not recommended and can be easily overwhelmed by a high volume of simultaneous requests.
    # Examples:
    # SQLite: "sqlite:///mypypi.db"
    # SQLite (in-memory): "sqlite:///:memory:"
    # PostgreSQL: "postgresql://username:password@localhost:5432/database"
    # PostgreSQL uses the psycopg2 driver. See this page for information on additional arguments: https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#psycopg2-connect-arguments

[storage]
    driver = "filesystem" # The storage driver to use. Valid options are "filesystem" and "s3"

[storage.s3]
    endpoint_url      = "https://s3.us-east-1.amazonaws.com" # The endpoint URL for the S3-compatible storage service
    access_key_id     = "{access_key_id}"                    # The access key ID for the S3-compatible storage service
    secret_access_key = "{secret_access_key}"                # The secret access key for the S3-compatible storage service
    region_name       = "us-east-1"                          # [Optional] The region name for the S3-compatible storage service. Cloudflare R2 uses "auto"
    bucket_name       = "mypypi-files"                       # The name of the bucket to store files in
    bucket_prefix     = ""                                   # [Optional] A prefix to add to all keys in the bucket
    public_url_prefix = "https://mycdn.example.com/pip/"     # Prefix to add to URLs for files stored in the S3-compatible storage service. This allows you to use a CDN or a separate domain to serve files from the storage provider. If using S3 without Cloudfront, this will be something like "https://mypypi-files.s3.us-east-1.amazonaws.com/"
    redirect_code     = 308                                  # [Optional] The HTTP status code to use for redirects to files stored in the S3-compatible storage service. Valid options are 301, 302, 307, 308. Defaults to 308.

[storage.filesystem]
    directory = "/data/" # If using the filesystem storage driver, this is the directory to store files in. Should be an absolute path.

[cache]
    driver = "redis" # The cache driver to use. Valid options are "memory", "filesystem", "redis", "memcached", and "database". Defaults to "memory".
    # The database cache driver will use the same database URL as the main database configuration

[cache.filesystem]
    directory = "/tmp/mypypi-cache/" # If using the filesystem cache driver, this is the directory to store files in. Should be an absolute path.

[cache.redis]
    # This driver will also work with Valkey
    host = "cache" # If using the redis cache driver, this is the host of the redis server. Can be a hostname or IP address.
    port = 6379    # The port of the redis server. Defaults to 6379.
    db   = 0       # The database number to use. Defaults to 0.

[cache.memcached]
    host = "cache" # If using the memcached cache driver, this is the host of the memcached server. Can be a hostname or IP address.
    port = 11211   # The port of the memcached server. Defaults to 11211.
