services:
  app:
    build: .
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - ./config.toml:/app/config.toml

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: mypypiuser
      POSTGRES_PASSWORD: mypypipass
      POSTGRES_DB: mypypi
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    restart: always

volumes:
  postgres-data: