name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release

jobs:
  test:
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.12"]

    uses: NathanVaughn/reusable-actions/.github/workflows/python-test-uv.yml@main
    with:
      python_version: ${{ matrix.python_version }}
